name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # create commits and releases
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node
        uses: ./.github/actions/node

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Publish
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_API_POST_RELEASE_MESSAGE: ${{ secrets.SLACK_API_POST_RELEASE_MESSAGE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "scope=@mvidalgarcia" > ~/.npmrc
          echo "access=public" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc
          yarn publish-packages
