name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: ./.github/actions/node

      - name: Publish
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_API_POST_RELEASE_MESSAGE: ${{ secrets.SLACK_API_POST_RELEASE_MESSAGE }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "hello publish job!"
          yarn publish-packages
